# Copyright 2026 mozc-date Project
# All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Generates the product version separately from Mozc's engine version.

MOZC_DATE_PRODUCT_VERSION overrides product_version.txt for release builds. The
three-component version is deliberately canonical: aliases such as 00.2.1
must not become distinct Git tags for the same Windows Installer version.
"""

import argparse
import dataclasses
import json
import os
import pathlib
import re
from collections.abc import Mapping


MSI_MAJOR_OFFSET = 100
_VERSION_PATTERN = re.compile(
    r'(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)'
)


@dataclasses.dataclass(frozen=True)
class ProductVersion:
  major: int
  minor: int
  patch: int

  @property
  def product_version(self) -> str:
    return f'{self.major}.{self.minor}.{self.patch}'

  @property
  def msi_version(self) -> str:
    # A reserved major range allows upgrading existing 3.x and 4.x packages
    # while keeping subsequent product releases ordered by major/minor/patch.
    return f'{MSI_MAJOR_OFFSET + self.major}.{self.minor}.{self.patch}'

  @property
  def release_tag(self) -> str:
    return f'v{self.product_version}'

  def as_manifest(self) -> dict[str, str]:
    return {
        'product_version': self.product_version,
        'msi_version': self.msi_version,
        'release_tag': self.release_tag,
    }


def parse_version(value: str) -> ProductVersion:
  """Validates a canonical version and the mapped MSI field limits."""
  match = _VERSION_PATTERN.fullmatch(value)
  if not match:
    raise ValueError(
        'Product version must be major.minor.patch with ASCII digits, no'
        ' leading zeroes, and no prerelease or build suffix: ' + repr(value)
    )
  components = match.groups()
  limits = (255 - MSI_MAJOR_OFFSET, 255, 65535)
  for name, component, limit in zip(
      ('major', 'minor', 'patch'), components, limits
  ):
    # Check length first so huge malformed inputs cannot overflow int parsing.
    if len(component) > len(str(limit)) or int(component) > limit:
      raise ValueError(
          f'Product {name} must be at most {limit} to fit MSI ProductVersion'
      )
  return ProductVersion(*(int(component) for component in components))


def read_version(
    version_file: pathlib.Path,
    version_override: str | None = None,
    environ: Mapping[str, str] | None = None,
) -> ProductVersion:
  """Reads CLI override, then nonempty environment override, then the file."""
  if version_override is not None:
    return parse_version(version_override)
  if environ is None:
    environ = os.environ
  environment_version = environ.get('MOZC_DATE_PRODUCT_VERSION', '')
  if environment_version:
    return parse_version(environment_version)
  return parse_version(version_file.read_text(encoding='utf-8').strip())


def read_manifest(path: pathlib.Path) -> ProductVersion:
  """Loads and verifies the manifest used by the installer and release CI."""
  manifest = json.loads(path.read_text(encoding='utf-8'))
  if not isinstance(manifest, dict) or not isinstance(
      manifest.get('product_version'), str
  ):
    raise ValueError(
        'Product version manifest must contain a product_version string'
    )
  version = parse_version(manifest['product_version'])
  if manifest != version.as_manifest():
    raise ValueError(
        'Product version manifest has inconsistent MSI version or release tag'
    )
  return version


def render_header(version: ProductVersion) -> str:
  return f'''// Generated by build_tools/product_version.py. Do not edit.
#ifndef MOZC_BASE_PRODUCT_VERSION_DEF_H_
#define MOZC_BASE_PRODUCT_VERSION_DEF_H_

namespace mozc {{
namespace version {{

inline constexpr char kProductVersion[] = "{version.product_version}";
inline constexpr char kMsiProductVersion[] = "{version.msi_version}";
inline constexpr char kProductReleaseTag[] = "{version.release_tag}";

}}  // namespace version
}}  // namespace mozc

#endif  // MOZC_BASE_PRODUCT_VERSION_DEF_H_
'''


def main(argv: list[str] | None = None) -> None:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument('--version_file', type=pathlib.Path, required=True)
  parser.add_argument('--version', help='Canonical major.minor.patch override')
  parser.add_argument('--header', type=pathlib.Path)
  parser.add_argument(
      '--output', type=pathlib.Path, help='JSON manifest output'
  )
  args = parser.parse_args(argv)
  if args.header is None and args.output is None:
    parser.error('At least one of --header or --output is required')
  try:
    version = read_version(args.version_file, args.version)
  except (OSError, ValueError) as error:
    parser.error(str(error))
  if args.header is not None:
    args.header.write_text(
        render_header(version), encoding='utf-8', newline='\n'
    )
  if args.output is not None:
    args.output.write_text(
        json.dumps(version.as_manifest(), indent=2) + '\n',
        encoding='utf-8',
        newline='\n',
    )


if __name__ == '__main__':
  main()
